framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'realstate@company.com'
        headers:
            From: 'Real State <realstate@company.com>'
            Bcc: 'baz@example.com'
            X-Custom-Header: 'foobar'